name = "CitableImage"
uuid = "17ccb2e5-db19-44b3-b354-4fd16d92c74e"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.1"

[deps]
CitableBase = "d6f014bd-995c-41bd-9893-703339864534"
CitableObject = "e2b2f5ea-1cd8-4ce8-9b2b-05dad64c2a57"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CitableBase = "1.1"
CitableObject = "0.2.1"
DocStringExtensions = "0.8"
Documenter = "0.26"
julia = "1.5"
